### ISSUE TITLE
Chrome 版本 42.0.2311.90 无法加载chromeapp

### ISSUE THREAD

**Issue by ayooay** [shadowsocks/shadowsocks-chromeapp#11]
无法加载以下来源的扩展程序： D:\game4fun\Chrome\shadowsocks-chromeapp-master
无法加载背景脚本“lib/logging.js”。

提示如下：
{
    "name":"Shadowsocks",
    "description":"Shadowsocks client for Chrome.",
    "version":"0.9",
    "manifest_version":2,
    "minimum_chrome_version": "41",
    "app":{

**Comment by meowlab** [comment]
请按照说明文件中的编译步骤编译CoffeeScript生成JavaScript文件

**Comment by ayooay** [comment]
嗯。刚才搞定了，发现里面都是CoffeeScript

**Comment by kanelau** [comment]
我完全菜鸟，也遇到上述错误。请问解答中的编译步骤。step by step 谢谢

**Comment by lweo** [comment]
@kanelau 
安装nodejs and CoffeeScript
运行coffee看是否成功，若
”/usr/bin/env: node: 没有那个文件或目录“

则
 sudo ln -s /usr/bin/nodejs /usr/bin/node

再cake build
