### ISSUE TITLE
请问一下为什么一直没有发布这个app呢？

### ISSUE THREAD

**Issue by wangnangg** [shadowsocks/shadowsocks-chromeapp#12]
等了好久也没看到它上架呀。

**Comment by meowlab** [comment]
因为本来计划会有一个重大更新的，但由于种种原因一直没有时间去做，所以就耽搁下来了。另外的考虑就是当前这个版本性能并不算太好，UI上也有欠缺，数据结构上也有点问题，发布的话可能不能保证向下兼容。
