### ISSUE TITLE
udp转发试用

### ISSUE THREAD

**Issue by Sunappnio** [shadowsocks/shadowsocks-chromeapp#13]
在chromebook上试用了udp转发，代理设置后打开谷歌似乎并没有QUIC的效果，
请问这个功能的具体使用场景在哪里？

**Comment by meowlab** [comment]
对QUIC不太熟悉，不知道chrome支不支持quic over socks5，感觉是不支持的
Socks5协议中有对udp的支持，所以就实现了，在Chromebook上也许没有具体的应用场景，但如果有用到需要udp支持的应用，就能发挥作用了

**Comment by Sunappnio** [comment]
@meowlab 好的，谢谢作者，没你这个我的chromebook就是砖头了（连不上google就会重复尝试然后死机）

**Comment by meowlab** [comment]
: )
