### ISSUE TITLE
如何解决？

### ISSUE THREAD

**Issue by luckypoem** [shadowsocks/shadowsocks-chromeapp#24]
hi.
Click Load Unpacked Extension，显示：
无法加载以下来源的扩展程序： ~/shadowsocks-chromeapp
无法加载背景脚本“lib/logging.js”。

**Comment by nekolab** [comment]
Hi, since this is a development version, you need to compile CoffeeScript to JavaScript by yourself.

As the note mentioned in Readme.md, you should install node.js and coffeescript, run cake build under the root directory, then load it to Chrome.

Cheers~

**Comment by luckypoem** [comment]
npm install coffee-script -g
cake build

that's all.tks

**Comment by luckypoem** [comment]
要是做成chrome的插件就更好了。那样才更方便，填入ss帐号的信息，即可使用的话，那样多好呢。

**Comment by nekolab** [comment]
Actually Chrome doesn't support socket api on extension architecture, so it's impossible.
