### ISSUE TITLE
求增加chacha20的支持

### ISSUE THREAD

**Issue by LBYPatrick** [shadowsocks/shadowsocks-chromeapp#28]
（虽然我也不知道能不能实现）如题，我同学的Macbook被上了密码，因此没有办法装小飞机客户端，我现在用的还是原版SS而不是新的SSR，求大神发功啊...跪谢

**Comment by nekolab** [comment]
很抱歉，根据 shadowsocks/shadowsocks-org/issues/36 的讨论，`chacha20`已经被弃用，不会再有后续支持了。`chacha20-ietf`会得到支持，但目前没有具体的时间表。
