### ISSUE TITLE
Would you please implement salsa20 cipher?

### ISSUE THREAD

**Issue by m13253** [shadowsocks/shadowsocks-chromeapp#29]
Most of my service providers switched to salsa20.
I hope ss-chromeapp can support salsa20, so that I can continue to use it.

I found a pure JavaScript implementation of salsa20 [here](https://github.com/neoatlantis/node-salsa20).

Will it be hard to integrate this cipher? I am willing to help.

**Comment by nekolab** [comment]
Hi, thanks for your remind and I don't think it would be hard to integrate, but as I noticed in https://github.com/shadowsocks/shadowsocks-chromeapp/issues/28, the chacha20/salsa20 ciphers were all deprecated, switch to other cipher should be a good idea.
