### ISSUE TITLE
这个项目弃坑了么

### ISSUE THREAD

**Issue by lostsnow** [shadowsocks/shadowsocks-chromeapp#30]
我看很久都没有更新了 `shadowsocks-nacl` 这个也没有新的内容了 还有后续的更新计划么 或者其他的替代品?

**Comment by nekolab** [comment]
感谢关注，可以说并没有打算弃坑，但面临很多不确定的因素

比如Chrome要在主流平台上取消对APP的支持[1]，这对开发调试都是很大的障碍，在Chromebook上调试是一件非常不舒服的事情。还有现有的API性能不尽如人意，V8的TypedArray会占用大量内存不积极释放，官方对PPAPI的开发停滞，加密解密无法使用硬件加速等问题。

SS方面最近协议引入了非常大的更新，目前评估认为插件系统是没有办法在Chrome APP上实现的，新的AEAD算法也需要一些时间去理解。非常抱歉的是一直没有足够的时间去做这件事情。

如果您使用Chromebook的话，也许可以尝试进入开发者模式编译安装libev版本的命令行客户端（无法确定可行性）

[1]: https://blog.chromium.org/2016/08/from-chrome-apps-to-web.html

**Comment by ghost** [comment]
从现在的情况看，在路由器上部署ss应该是最好的处理方式
