### ISSUE TITLE
 Could not load background script 'lib/logging.js

### ISSUE THREAD

**Issue by locochen** [shadowsocks/shadowsocks-chromeapp#34]
_Chrome_ Version 58.0.3029.110 _(64-bit)_

Error Loading Extension
Failed to load extension from: ~\Downloads\Compressed\shadowsocks-chromeapp-master\shadowsocks-chromeapp-master
Could not load background script 'lib/logging.js'.

**Comment by nekolab** [comment]
Please follow the compile instructions in readme.md

**Comment by wyfwyf112** [comment]
I followed the instruction and got the error code.
