### ISSUE TITLE
about pac

### ISSUE THREAD

**Issue by yjgbg** [shadowsocks/shadowsocks-chromeapp#36]
Perhats it's a  overly request, I think it will be better when the app has pac.
sorry for my poor english

**Comment by nekolab** [comment]
Actually chrome app (not extension) doesn't support `chrome.proxy` API, so there is no way to support PAC in chrome app.

Besides, the chrome extension doesn't support `chrome.sockets` API, which is the infrastructure of this app, so migrate this app to extension is not possible too.

Thanks for you advice~
