### ISSUE TITLE
error: 无法加载背景脚本“lib/logging.js”。

### ISSUE THREAD

**Issue by joegege** [shadowsocks/shadowsocks-chromeapp#4]
Why always show error below: 
无法加载以下来源的扩展程序： ~/Downloads/shadowsocks-chromeapp-aes/shadowsocks-chromeapp-master
无法加载背景脚本“lib/logging.js”。

**Comment by meowlab** [comment]
Hello, since this is a development version, you need compile CoffeeScript to JavaScript by yourselves.
As the note mentioned in Readme.md, you should install node.js and coffeescript, run `cake build` under the root directory, then load it to Chrome.
Cheers~

**Comment by joegege** [comment]
Thanks for prompt reply. Seems difficult for me to compile it. I will waiting for the final normal version.
:)

**Comment by meowlab** [comment]
Happy to see you are concerned about this project, hope one day it can be published to Chrome Web Store :)
