### ISSUE TITLE
我可以上传到Chrome应用商店里面去吗

### ISSUE THREAD

**Issue by Thron-LEE** [shadowsocks/shadowsocks-chromeapp#7]

**Comment by meowlab** [comment]
最好不要，我觉得现在的版本并不稳定，发布以后如果未来要大改的话必将涉及到向下兼容，这方面会比较麻烦。

@clowwindy 
其实我也考虑过发布到 Chrome WebStore，但除了向下兼容的考虑以外，还不知道应该以我个人的身份发布还是使用Shadowsocks的官方账户发布，Shadowsocks的各个port在这方面有什么讲究吗？

**Comment by Thron-LEE** [comment]
​好的，感谢你的答复​

**Comment by clowwindy** [comment]
可以考虑公用一个

**Comment by himulawang** [comment]
支持！期待快点完工。

**Comment by forestzhang945** [comment]
是不是少了lib文件夹内容，无法成功打包

**Comment by meowlab** [comment]
@forestzhang945 请根据readme文件进行编译生成lib文件夹
