### ISSUE TITLE
Where is the lib folder?

### ISSUE THREAD

**Issue by itcyh** [shadowsocks/shadowsocks-chromeapp#8]

**Comment by meowlab** [comment]
Follow the build instruction to generate one.

**Comment by itcyh** [comment]
I am a novice.Could you tell me how to do?thanks!@meowlab

**Comment by meowlab** [comment]
First install nodejs and coffeescript (`npm install coffeescript`).
Clone this repository, go to the root directory of the repo, run `cake build` to generate one.

**Comment by itcyh** [comment]
Thanks,but why is it all the time  'Listening on port'.@meowlab

**Comment by meowlab** [comment]
Yes...it's by design.
What else do you want to see?

**Comment by itcyh** [comment]
Oh,thanks!@meowlab
