### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by solo-code** [shadowsocks/shadowsocks-chromeapp#9]
错误信息：
~/source_soft/shadowsocks-chromeapp-master$ cake build
PHP Warning:  /usr/share/php/cake/console/templates/skel/tmp/cache/ is not writable in /usr/share/php/cake/libs/cache/file.php on line 281

Warning: /usr/share/php/cake/console/templates/skel/tmp/cache/ is not writable in /usr/share/php/cake/libs/cache/file.php on line 281
Error: Class BuildShell could not be loaded.

**Comment by meowlab** [comment]
Seems you are using CakePHP to build this project, it's not the correct toolchain.
You should install nodejs and coffeescript, then use coffeescript's `cake` to build it,

**Comment by solo-code** [comment]
Thank you!



solocode@sina.com
 
From: 喵星实验室
Date: 2015-05-02 00:19
To: shadowsocks/shadowsocks-chromeapp
CC: solocode
Subject: Re: [shadowsocks-chromeapp] build error (#9)
Seems you are using CakePHP to build this project, it's not the correct toolchain.
You should install nodejs and coffeescript, then use coffeescript's cake to build it,
